---
name: Issue with the Public Web Api
description: Report an issue with the Public Web Api
title: "**short summary**"
labels: ["question", "webapi"]
body:

- type: markdown
  attributes:
    value: |
      Please fill out the information in this issue template so that we can efficiently process your request
      
      https://date.nager.at/api
      https://date.nager.at/swagger/index.html

- type: input
  id: endpoint
  attributes:
    label: Endpoint
    description: "Which endpoint is affected"
    placeholder: "api/v3/PublicHolidays/2017/AT"
  validations:
    required: true

- type: textarea
  id: information
  attributes:
    label: More information
    description: "You can enter more information here."
  validations:
    required: true