---
name: Issue with the docker container
description: Report an issue with the docker container
title: "**short summary**"
labels: ["question", "docker"]
body:

- type: markdown
  attributes:
    value: |
      Please fill out the information in this issue template so that we can efficiently process your request
      
      https://hub.docker.com/r/nager/nager-date

- type: input
  id: dockertag
  attributes:
    label: Docker TAG
    description: "Which version of the Docker Container is affected"
    placeholder: "build-20"
  validations:
    required: true

- type: textarea
  id: information
  attributes:
    label: More information
    description: "You can enter more information here."
  validations:
    required: true
